# Site settings
title: Nightly Build
author: JScott
email: jvscott@gmail.com
description: "Pushing the boundaries of spare time"
baseurl: "/blog" # comment out if site is in root folder
url: "http://www.jvscott.net"
more: "read more"

# Comments
disqus_username: "goonmygoon@gmail.com"
#isso_domain: "comments.mysite.org"

# Links

links:
  - github: "https://github.com/JScott/"
  - twitter: "https://twitter.com/AKindlyOrc/"
#  - google-plus: "https://plus.google.com/+me"
#  - reddit: "https://www.reddit.com/user/me/"
#  - youtube: "https://www.youtube.com/user/me"
#  - steam: "http://steamcommunity.com/id/me/"


# Build settings
markdown: redcarpet
permalink: /:title/
excerpt_separator: "<!--more-->"

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
