name: Nightly Build
url: http://jvscott.net
baseurl: /blog
description: ''
#Pushing the boundaries of spare time

twitter: AKindlyOrc

#permalink: /:year/:month/:day/:title/
permalink: /:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
